# Generated by Django 4.2 on 2026-05-03 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationType',
            fields=[
                ('relationship_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'association_type',
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('char_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('char_class_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Character Classes',
                'db_table': 'character_class',
            },
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('char_race_id', models.AutoField(primary_key=True, serialize=False)),
                ('char_race_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'character_race',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('char_name', models.CharField(max_length=100)),
                ('char_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('backstory_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('char_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characterclass')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characterrace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='CharacterAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_from', to='characters.character')),
                ('relationship_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.associationtype')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_to', to='characters.character')),
            ],
            options={
                'db_table': 'character_association',
                'unique_together': {('from_character', 'to_character', 'relationship_type')},
            },
        ),
    ]
